#ifndef Path_h
#define Path_h

#include <string>

/*
 This file's content is generated by the script!

 xcode: mac/generate_path.sh
 visual studio: windows\generate_path.bat
*/

#ifdef __APPLE__
	const std::string ProjectPath = "<Absolute path>/LearnOpenGL";
#else
	const std::string ProjectPath = R"(<Absolute path>/LearnOpenGL)";
#endif

#endif /* Path_h */
